#ifndef __WEB_PAGE_H__INCLUDED__
#define __WEB_PAGE_H__INCLUDED__

const char* INDEX_HTML = 
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"    <meta charset='UTF-8'>"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"    <title>ESP32-C6 Accel Dashboard</title>"
"    <style>"
"        body {"
"            margin: 0;"
"            padding: 0;"
"            background: radial-gradient(circle at center, #1b2735 0%, #090a0f 100%);"
"            color: #ffffff;"
"            font-family: 'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"
"            display: flex;"
"            flex-direction: column;"
"            align-items: center;"
"            justify-content: center;"
"            min-height: 100vh;"
"            overflow-x: hidden;"
"        }"
"        .header {"
"            text-align: center;"
"            margin-bottom: 20px;"
"        }"
"        .header h1 {"
"            margin: 0;"
"            font-size: 2.2rem;"
"            background: linear-gradient(45deg, #00f2fe, #4facfe);"
"            -webkit-background-clip: text;"
"            -webkit-text-fill-color: transparent;"
"            font-weight: 700;"
"        }"
"        .status {"
"            display: inline-flex;"
"            align-items: center;"
"            gap: 8px;"
"            font-size: 0.9rem;"
"            color: #8fa0b5;"
"            margin-top: 5px;"
"        }"
"        .dot {"
"            width: 10px;"
"            height: 10px;"
"            background-color: #00e676;"
"            border-radius: 50%;"
"            box-shadow: 0 0 10px #00e676;"
"            animation: pulse 1.5s infinite;"
"        }"
"        @keyframes pulse {"
"            0% { opacity: 0.4; }"
"            50% { opacity: 1; }"
"            100% { opacity: 0.4; }"
"        }"
"        .container {"
"            display: grid;"
"            grid-template-columns: 1fr;"
"            gap: 24px;"
"            max-width: 1000px;"
"            width: 90%;"
"            padding: 20px;"
"        }"
"        @media(min-width: 768px) {"
"            .container {"
"                grid-template-columns: 1fr 1fr;"
"            }"
"        }"
"        .card {"
"            background: rgba(255, 255, 255, 0.05);"
"            backdrop-filter: blur(12px);"
"            -webkit-backdrop-filter: blur(12px);"
"            border: 1px solid rgba(255, 255, 255, 0.1);"
"            border-radius: 16px;"
"            padding: 24px;"
"            display: flex;"
"            flex-direction: column;"
"            align-items: center;"
"            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);"
"            box-sizing: border-box;"
"        }"
"        .card h2 {"
"            margin-top: 0;"
"            margin-bottom: 20px;"
"            font-size: 1.3rem;"
"            color: #00f2fe;"
"            font-weight: 600;"
"            width: 100%;"
"            border-bottom: 1px solid rgba(255, 255, 255, 0.1);"
"            padding-bottom: 10px;"
"            text-align: center;"
"        }"
"        .scene {"
"            width: 200px;"
"            height: 200px;"
"            perspective: 600px;"
"            display: flex;"
"            align-items: center;"
"            justify-content: center;"
"            margin: 20px 0;"
"        }"
"        .cube {"
"            width: 100px;"
"            height: 100px;"
"            position: relative;"
"            transform-style: preserve-3d;"
"            transition: transform 0.1s ease-out;"
"        }"
"        .face {"
"            position: absolute;"
"            width: 100px;"
"            height: 100px;"
"            border: 2px solid #00f2fe;"
"            background: rgba(0, 242, 254, 0.15);"
"            display: flex;"
"            align-items: center;"
"            justify-content: center;"
"            font-weight: bold;"
"            font-size: 1.2rem;"
"            color: #ffffff;"
"            box-sizing: border-box;"
"            border-radius: 4px;"
"        }"
"        .front  { transform: rotateY(  0deg) translateZ(50px); border-color: #00f2fe; background: rgba(0,242,254,0.15); }"
"        .back   { transform: rotateY(180deg) translateZ(50px); border-color: #ff007f; background: rgba(255,0,127,0.15); }"
"        .right  { transform: rotateY( 90deg) translateZ(50px); border-color: #00e676; background: rgba(0,230,118,0.15); }"
"        .left   { transform: rotateY(-90deg) translateZ(50px); border-color: #ffeb3b; background: rgba(255,235,59,0.15); }"
"        .top    { transform: rotateX( 90deg) translateZ(50px); border-color: #29b6f6; background: rgba(41,182,246,0.15); }"
"        .bottom { transform: rotateX(-90deg) translateZ(50px); border-color: #ab47bc; background: rgba(171,71,188,0.15); }"
"        .bar-container {"
"            width: 100%;"
"            display: flex;"
"            flex-direction: column;"
"            gap: 16px;"
"        }"
"        .bar-group {"
"            display: flex;"
"            flex-direction: column;"
"            gap: 6px;"
"        }"
"        .bar-label-row {"
"            display: flex;"
"            justify-content: space-between;"
"            font-size: 0.95rem;"
"            font-weight: 500;"
"        }"
"        .bar-bg {"
"            width: 100%;"
"            height: 14px;"
"            background: rgba(255, 255, 255, 0.1);"
"            border-radius: 7px;"
"            overflow: hidden;"
"            position: relative;"
"        }"
"        .bar-fill {"
"            height: 100%;"
"            width: 50%;"
"            border-radius: 7px;"
"            transition: width 0.1s ease-out, background-color 0.3s;"
"        }"
"        #bar-x { background: linear-gradient(90deg, #00c6ff, #0072ff); }"
"        #bar-y { background: linear-gradient(90deg, #f9d423, #ff4e50); }"
"        #bar-z { background: linear-gradient(90deg, #96fbc4, #f9f586); }"
"        .val-num {"
"            font-family: monospace;"
"            font-size: 1.1rem;"
"        }"
"        .arrow-pad {"
"            display: grid;"
"            grid-template-rows: auto auto;"
"            align-items: center;"
"            justify-content: center;"
"            gap: 20px;"
"            margin: 30px 0;"
"            width: 100%;"
"        }"
"        .arrow-row {"
"            display: flex;"
"            justify-content: center;"
"            gap: 40px;"
"        }"
"        .arrow-svg {"
"            width: 64px;"
"            height: 64px;"
"            fill: #34495e;"
"            filter: drop-shadow(0 0 2px rgba(0,0,0,0.5));"
"            transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);"
"            opacity: 0.65;"
"            cursor: pointer;"
"            -webkit-user-select: none;"
"            user-select: none;"
"        }"
"        .arrow-svg:hover {"
"            opacity: 0.95;"
"            transform: scale(1.08);"
"        }"
"        #arrow-fwd.active, .arrow-svg:active {"
"            fill: #00f2fe;"
"            filter: drop-shadow(0 0 15px #00f2fe);"
"            opacity: 1;"
"            transform: scale(1.15);"
"        }"
"        #arrow-left.active {"
"            fill: #f9d423;"
"            filter: drop-shadow(0 0 15px #f9d423);"
"            opacity: 1;"
"            transform: scale(1.15);"
"        }"
"        #arrow-right.active {"
"            fill: #00e676;"
"            filter: drop-shadow(0 0 15px #00e676);"
"            opacity: 1;"
"            transform: scale(1.15);"
"        }"
"        .dist-num-wrap {"
"            margin: 20px 0 10px 0;"
"            text-align: center;"
"        }"
"        .dist-num {"
"            font-size: 3.5rem;"
"            font-weight: 700;"
"            color: #00f2fe;"
"            font-family: monospace;"
"            text-shadow: 0 0 10px rgba(0, 242, 254, 0.3);"
"        }"
"        .dist-unit {"
"            font-size: 1.2rem;"
"            color: #8fa0b5;"
"            margin-left: 5px;"
"        }"
"        .dist-bg {"
"            width: 100%;"
"            height: 20px;"
"            background: rgba(255, 255, 255, 0.1);"
"            border-radius: 10px;"
"            overflow: hidden;"
"            position: relative;"
"            margin-top: 20px;"
"            box-shadow: inset 0 2px 4px rgba(0,0,0,0.5);"
"        }"
"        .dist-bar {"
"            height: 100%;"
"            width: 100%;"
"            border-radius: 10px;"
"            background: #00e676;"
"            transition: width 0.2s ease-out, background 0.3s;"
"            box-shadow: 0 0 8px rgba(0,230,118,0.5);"
"        }"
"    </style>"
"    <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&display=swap' rel='stylesheet'>"
"</head>"
"<body>"
"    <div class='header'>"
"        <h1>ESP32-C6 Accel Dashboard</h1>"
"        <div class='status'>"
"            <div class='dot' id='status-dot'></div>"
"            <span id='status-text'>Live Data (SoftAP)</span>"
"        </div>"
"    </div>"
"    "
"    <div class='container'>"
"        <div class='card'>"
"            <h2>3D Orientation</h2>"
"            <div class='scene'>"
"                <div class='cube' id='cube'>"
"                    <div class='face front'>X+</div>"
"                    <div class='face back'>X-</div>"
"                    <div class='face right'>Y+</div>"
"                    <div class='face left'>Y-</div>"
"                    <div class='face top'>Z+</div>"
"                    <div class='face bottom'>Z-</div>"
"                </div>"
"            </div>"
"        </div>"
"        "
"        <div class='card'>"
"            <h2>Motor Controls</h2>"
"            <div class='arrow-pad'>"
"                <div class='arrow-row'>"
"                    <svg class='arrow-svg' id='arrow-fwd' viewBox='0 0 24 24'>"
"                        <path d='M12 4l-8 8h6v8h4v-8h6z'/>"
"                    </svg>"
"                </div>"
"                <div class='arrow-row'>"
"                    <svg class='arrow-svg' id='arrow-left' viewBox='0 0 24 24'>"
"                        <path d='M4 12l8-8v6h8v4h-8v6z'/>"
"                    </svg>"
"                    <svg class='arrow-svg' id='arrow-right' viewBox='0 0 24 24'>"
"                        <path d='M20 12l-8-8v6h-8v4h8v6z'/>"
"                    </svg>"
"                </div>"
"            </div>"
"        </div>"
"        "
"        <div class='card'>"
"            <h2>Distance Sensor</h2>"
"            <div class='dist-num-wrap'>"
"                <span id='val-dist' class='dist-num'>0.0</span>"
"                <span class='dist-unit'>cm</span>"
"            </div>"
"            <div class='dist-bg'>"
"                <div class='dist-bar' id='dist-bar'></div>"
"            </div>"
"        </div>"
"        "
"        <div class='card'>"
"            <h2>G-Force Metrics</h2>"
"            <div class='bar-container'>"
"                <div class='bar-group'>"
"                    <div class='bar-label-row'>"
"                        <span style='color: #00c6ff;'>X Axis (Pitch)</span>"
"                        <span id='val-x' class='val-num'>0.000 g</span>"
"                    </div>"
"                    <div class='bar-bg'>"
"                        <div class='bar-fill' id='bar-x'></div>"
"                    </div>"
"                </div>"
"                "
"                <div class='bar-group'>"
"                    <div class='bar-label-row'>"
"                        <span style='color: #f9d423;'>Y Axis (Roll)</span>"
"                        <span id='val-y' class='val-num'>0.000 g</span>"
"                    </div>"
"                    <div class='bar-bg'>"
"                        <div class='bar-fill' id='bar-y'></div>"
"                    </div>"
"                </div>"
"                "
"                <div class='bar-group'>"
"                    <div class='bar-label-row'>"
"                        <span style='color: #96fbc4;'>Z Axis</span>"
"                        <span id='val-z' class='val-num'>0.000 g</span>"
"                    </div>"
"                    <div class='bar-bg'>"
"                        <div class='bar-fill' id='bar-z'></div>"
"                    </div>"
"                </div>"
"            </div>"
"        </div>"
"    </div>"
"    <script>"
"        const cube = document.getElementById('cube');"
"        const valX = document.getElementById('val-x');"
"        const valY = document.getElementById('val-y');"
"        const valZ = document.getElementById('val-z');"
"        const barX = document.getElementById('bar-x');"
"        const barY = document.getElementById('bar-y');"
"        const barZ = document.getElementById('bar-z');"
"        const arrowFwd = document.getElementById('arrow-fwd');"
"        const arrowLeft = document.getElementById('arrow-left');"
"        const arrowRight = document.getElementById('arrow-right');"
"        const valDist = document.getElementById('val-dist');"
"        const distBar = document.getElementById('dist-bar');"
"        const statusDot = document.getElementById('status-dot');"
"        const statusText = document.getElementById('status-text');"
""
"        /* Motor Control Event Senders */"
"        let currentDir = 'stop';"
"        function sendMotorCommand(dir) {"
"            if (currentDir === dir) return;"
"            currentDir = dir;"
"            "
"            /* Set active states programmatically for immediate feedback */"
"            arrowFwd.classList.toggle('active', dir === 'fwd');"
"            arrowLeft.classList.toggle('active', dir === 'left');"
"            arrowRight.classList.toggle('active', dir === 'right');"
"            "
"            fetch('/motor?dir=' + dir)"
"                .catch(err => console.error('Error sending motor command:', err));"
"        }"
""
"        function setupMotorButton(btn, dir) {"
"            btn.addEventListener('mousedown', () => sendMotorCommand(dir));"
"            btn.addEventListener('mouseup', () => sendMotorCommand('stop'));"
"            btn.addEventListener('mouseleave', () => sendMotorCommand('stop'));"
"            btn.addEventListener('touchstart', (e) => {"
"                e.preventDefault();"
"                sendMotorCommand(dir);"
"            });"
"            btn.addEventListener('touchend', (e) => {"
"                e.preventDefault();"
"                sendMotorCommand('stop');"
"            });"
"        }"
""
"        setupMotorButton(arrowFwd, 'fwd');"
"        setupMotorButton(arrowLeft, 'left');"
"        setupMotorButton(arrowRight, 'right');"
""
"        function updateUI(x, y, z, dist) {"
"            valX.textContent = x.toFixed(3) + ' g';"
"            valY.textContent = y.toFixed(3) + ' g';"
"            valZ.textContent = z.toFixed(3) + ' g';"
"            const pctX = Math.min(Math.max((x + 2) / 4 * 100, 0), 100);"
"            const pctY = Math.min(Math.max((y + 2) / 4 * 100, 0), 100);"
"            const pctZ = Math.min(Math.max((z + 2) / 4 * 100, 0), 100);"
"            barX.style.width = pctX + '%';"
"            barY.style.width = pctY + '%';"
"            barZ.style.width = pctZ + '%';"
"            const pitch = Math.atan2(x, Math.sqrt(y * y + z * z)) * (180 / Math.PI);"
"            const roll = Math.atan2(y, z) * (180 / Math.PI);"
"            cube.style.transform = 'rotateX(' + (-pitch) + 'deg) rotateY(' + roll + 'deg)';"
"            if (dist < 0) {"
"                valDist.textContent = '---';"
"                distBar.style.width = '0%';"
"            } else {"
"                valDist.textContent = dist.toFixed(1);"
"                const pctDist = Math.min(Math.max(dist / 100 * 100, 0), 100);"
"                distBar.style.width = pctDist + '%';"
"                if (dist < 10) {"
"                    distBar.style.background = 'linear-gradient(90deg, #ff0055, #ff007f)';"
"                    distBar.style.boxShadow = '0 0 10px #ff007f';"
"                } else if (dist < 30) {"
"                    distBar.style.background = 'linear-gradient(90deg, #f1c40f, #f9d423)';"
"                    distBar.style.boxShadow = '0 0 10px #f9d423';"
"                } else {"
"                    distBar.style.background = 'linear-gradient(90deg, #2ecc71, #00e676)';"
"                    distBar.style.boxShadow = '0 0 10px #00e676';"
"                }"
"            }"
"        }"
"        function pollData() {"
"            fetch('/data?_t=' + new Date().getTime())"
"                .then(response => {"
"                    if (!response.ok) throw new Error('HTTP error ' + response.status);"
"                    return response.json();"
"                })"
"                .then(data => {"
"                    statusDot.style.backgroundColor = '#00e676';"
"                    statusDot.style.boxShadow = '0 0 10px #00e676';"
"                    statusText.textContent = 'Live Data (SoftAP)';"
"                    updateUI(data.x, data.y, data.z, data.dist);"
"                })"
"                .catch(err => {"
"                    console.error('Error fetching data:', err);"
"                    statusDot.style.backgroundColor = '#ff0055';"
"                    statusDot.style.boxShadow = '0 0 10px #ff0055';"
"                    statusText.textContent = 'Disconnected';"
"                });"
"        }"
"        setInterval(pollData, 150);"
"    </script>"
"</body>"
"</html>";

#endif // __WEB_PAGE_H__INCLUDED__
